### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jhen0409** [mybigday/react-native-media-meta#1]
- [ ] thumb - support get frame by time
- [ ] thumb - support resize

# iOS

- [ ] Use FFmpegMediaMetadataRetriever iOS instead of AVMatadataItem
